name: firebase_inti
description: A new Flutter project.

publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  google_generative_ai: ^0.4.6





  # REQUIRED PACKAGES
  firebase_core: ^3.0.0
  cloud_firestore: ^5.0.0
  http: ^1.2.1
  provider: ^6.1.2
  uuid: ^4.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
